BRUTE_FORCE_THRESHOLD = 5
BRUTE_FORCE_WINDOW_MINUTES = 5

SUCCESS_AFTER_FAILURES_THRESHOLD = 3
SUCCESS_AFTER_FAILURES_WINDOW_MINUTES = 5

PASSWORD_SPRAY_USER_THRESHOLD = 4
PASSWORD_SPRAY_WINDOW_MINUTES = 5

CREDENTIAL_STUFFING_USER_THRESHOLD = 3
CREDENTIAL_STUFFING_FAILURE_THRESHOLD = 5
CREDENTIAL_STUFFING_WINDOW_MINUTES = 10

MULTI_ACCOUNT_TARGET_USER_THRESHOLD = 3
MULTI_ACCOUNT_TARGET_WINDOW_MINUTES = 10

ANOMALOUS_LOGIN_BURST_THRESHOLD = 5
ANOMALOUS_LOGIN_BURST_WINDOW_MINUTES = 1

PRIVILEGED_USERS = {
    "admin",
    "administrator",
    "root"
}